// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
)

type CreateOrderRequest struct {
	UserID  int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	Product string `thrift:"product,2" frugal:"2,default,string" json:"product"`
}

func NewCreateOrderRequest() *CreateOrderRequest {
	return &CreateOrderRequest{}
}

func (p *CreateOrderRequest) InitDefault() {
}

func (p *CreateOrderRequest) GetUserID() (v int64) {
	return p.UserID
}

func (p *CreateOrderRequest) GetProduct() (v string) {
	return p.Product
}
func (p *CreateOrderRequest) SetUserID(val int64) {
	p.UserID = val
}
func (p *CreateOrderRequest) SetProduct(val string) {
	p.Product = val
}

func (p *CreateOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderRequest(%+v)", *p)
}

var fieldIDToName_CreateOrderRequest = map[int16]string{
	1: "userID",
	2: "product",
}

type OrderInfo struct {
	OrderID  int64  `thrift:"orderID,1" frugal:"1,default,i64" json:"orderID"`
	UserID   int64  `thrift:"userID,2" frugal:"2,default,i64" json:"userID"`
	Product  string `thrift:"product,3" frugal:"3,default,string" json:"product"`
	UserName string `thrift:"userName,4" frugal:"4,default,string" json:"userName"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetOrderID() (v int64) {
	return p.OrderID
}

func (p *OrderInfo) GetUserID() (v int64) {
	return p.UserID
}

func (p *OrderInfo) GetProduct() (v string) {
	return p.Product
}

func (p *OrderInfo) GetUserName() (v string) {
	return p.UserName
}
func (p *OrderInfo) SetOrderID(val int64) {
	p.OrderID = val
}
func (p *OrderInfo) SetUserID(val int64) {
	p.UserID = val
}
func (p *OrderInfo) SetProduct(val string) {
	p.Product = val
}
func (p *OrderInfo) SetUserName(val string) {
	p.UserName = val
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1: "orderID",
	2: "userID",
	3: "product",
	4: "userName",
}

type CreateOrderResponse struct {
	Order   *OrderInfo `thrift:"order,1" frugal:"1,default,OrderInfo" json:"order"`
	Message string     `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewCreateOrderResponse() *CreateOrderResponse {
	return &CreateOrderResponse{}
}

func (p *CreateOrderResponse) InitDefault() {
}

var CreateOrderResponse_Order_DEFAULT *OrderInfo

func (p *CreateOrderResponse) GetOrder() (v *OrderInfo) {
	if !p.IsSetOrder() {
		return CreateOrderResponse_Order_DEFAULT
	}
	return p.Order
}

func (p *CreateOrderResponse) GetMessage() (v string) {
	return p.Message
}
func (p *CreateOrderResponse) SetOrder(val *OrderInfo) {
	p.Order = val
}
func (p *CreateOrderResponse) SetMessage(val string) {
	p.Message = val
}

func (p *CreateOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *CreateOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResponse(%+v)", *p)
}

var fieldIDToName_CreateOrderResponse = map[int16]string{
	1: "order",
	2: "message",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (r *CreateOrderResponse, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderRequest `thrift:"req,1" frugal:"1,default,CreateOrderRequest" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderRequest

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderRequest) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderRequest) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResponse

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResponse)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}
